from typing import Protocol

from data_platform_mcp.models import DagInfo, SearchHit, TableInfo, TableStatistics


class CatalogAdapter(Protocol):
    def list_sources(self) -> list[str]: ...
    def list_schemas(self, source: str) -> list[str]: ...
    def list_tables(self, source: str, schema: str) -> list[str]: ...
    def describe_table(self, source: str, schema: str, table: str) -> TableInfo: ...
    def table_statistics(self, source: str, schema: str, table: str) -> TableStatistics: ...
    def explain_sql(self, source: str, sql: str) -> str: ...


class OperationsAdapter(Protocol):
    def list_dags(self) -> list[DagInfo]: ...
    def get_dag_status(self, dag_id: str) -> DagInfo: ...


class LogSearchAdapter(Protocol):
    def search(self, query: str, limit: int = 10) -> list[SearchHit]: ...


class RunbookAdapter(Protocol):
    def search(self, query: str, limit: int = 10) -> list[SearchHit]: ...
